name: prepare
description: prepare development environment

runs:
  using: 'composite'
  steps:
    - uses: DeterminateSystems/determinate-nix-action@v3.6.2
    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv
