name: ci

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: "ci"
  cancel-in-progress: false

defaults:
  run:
    shell: devenv shell bash -- -e {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: Build
        run: build
